### ISSUE TITLE
Online version.

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/styleguide#5]
Currently this styleguide is viewable as top-level content at:

https://daq.dunescience.org/

There are a few problems that need fixing:

- [ ] remove Google branding 
- [ ] fix links to point back into our style guide content and not google's
- [ ] move content to a sub-path eg `/styleguide/` (the DAQ is more than the styleguide!) to make room for other DAQ pages
- [ ] provide initial landing page that provides a link to the moved styleguide URL

**Comment by dingp** [comment]
Hi Brett,

Thanks for checking the page. It was left after the initial test of hosting webpages by Github. These pages point to the a branch in the `stygleguide` repo. The URL https://daq.dunescience.org points to https://dune-daq.github.io/styleguide/dune-daq-cppguide (done by a CNAME record on Fermilab's side).

We are thinking about organizing the docs better, either with Mkdocs or other tools (Jekyll?). And certainly, the top level of the site should not be with the `styleguide` repo. It is likely going to be an umbrella repo with submodules of all other repos, or duplicated docs files copied over from other repos.

For the moment, I'm turning off the URL redirection to avoid confusion, and release it future once we have a better setup ready.

Best,
Pengfei

**Comment by dingp** [comment]
I believe this issue is resolved after we moved to readthedocs.
